name: McMiniMap
main: me.supermaxman.mcminimap.McMiniMap
version: 1.0.0
author: Supermaxman
description: MiniMap In Minecraft
commands:
    minimaptoggle:
        description: 
        usage: /<command> toggle
    mmt:
        description: 
        usage: /<command> toggle
    minimapzoomin:
        description: 
        usage: /<command>
    minimapzoomout:
        description: 
        usage: /<command>